---
# Set to yes, if you're using pycharm for development
# Otherwise, set no
use_pycharm: yes
# Your linux/mac user that will run ansible
remote_user: lucernae
# Your linux/mac group that will run ansible
remote_group: staff
# Your project location (this repo)
project_path: "/Users/lucernae/Documents/WorkingDir/Projects/kartoza/scanwebgis-docker"
# True if it will be running on Travis
on_travis: False
# Project name as pycharm namespace
project_name: scanwebgis-docker

django:
  # extra django app location from deployment folder
  app_location: ../django_project
  volumes:
    - ../submodules/scanwebgis/django_app:/home/web/extra_app
  environment:
    GEONODE_PREFIX: "''"
    SITE_DOMAIN_NAME: 'http://scanwebgis-docker.test:63302'
    GEOCONTEXT_URL: 'http://localhost:65402'
    CONTACT_US_EMAIL: 'dimas@kartoza.com'
    DEBUG: True
    # Put random string on secret key
    SECRET_KEY: 2510)aks1u*9mgjjss_+s1@rutm3v(sfv5hw8k#*t(jsdmg-
    DJANGO_SETTINGS_MODULE: core.settings.overrides
    RABBITMQ_HOST: rabbitmq
    HAYSTACK_HOST: elasticsearch
    PYTHONPATH: /usr/src/app:/home/web/django_project:/home/web/extra_app
    ROOT_URLCONF: core.root_urls
    DATABASE_NAME: gis
    DATABASE_PASSWORD: docker
    DATABASE_USERNAME: docker
    DATABASE_HOST: db
    SITEURL: http://scanwebgis-docker.test:63302/
    SCANWEBGIS_URL: http://scanwebgis-docker.test:63306/scanwebgis/

scanwebgis:
  command: /usr/sbin/sshd -D
  volumes:
    - ../submodules/scanwebgis/django_app:/home/web/extra_app
  environment:
    # Put random string on secret key
    DJANGO_SECRET_KEY: 2510)aks1u*9mgjjss_+s1@rutm3v(sfv5hw8k#*t(jsdmg-
    PYTHONPATH: /home/web/extra_app
    ROOT_URLCONF: scanterra.urls
    URL_PREFIX: 'scanwebgis/'
    DEBUG: True
    DJANGO_SETTINGS_MODULE: scanterra.settings_prod
    SITEURL: http://scanwebgis-docker.test:63306/
    STATIC_ROOT: /home/web/static
    MEDIA_ROOT: /home/web/media
    # For database
    PGDATABASE: scanweb
    PGUSER: docker
    PGPASSWORD: docker
    PGHOST: db
    PGPORT: 5432
    # For GeoNode
    GEONODE_SERVER_HOST: http://scanwebgis-docker.test:63302
    GEOSERVER_SERVER_HOST: http://scanwebgis-docker.test:63305
    # For KOBO
    # To Kobocat
    KOBO_API_URL: http://test.scancollect.scanterra.com
    KOBO_API_CLIENTID: ''
    KOBO_API_CLIENTSECRET: ''
    KOBO_API_USER: ''
    KOBO_API_PASSWORD: ''
    # Redis Settings
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_DEFAULT_DB: 1
    REDIS_SESSION_DB: 2


geonode:
  environment:
    GEONODE_INSTANCE_NAME: geonode
    DEFAULT_BACKEND_DATASTORE: datastore
    GEONODE_DATABASE: gis
    GEONODE_DATABASE_USER: docker
    GEONODE_DATABASE_PASSWORD: docker
    GEONODE_GEODATABASE: geonode_data
    GEONODE_GEODATABASE_PASSWORD: geonode_data
    UWSGI_CMD: uwsgi --ini /usr/src/app/uwsgi.ini
    IS_CELERY: False
    C_FORCE_ROOT: 1
    # replaced with defaults in settings
    GEOSERVER_BASE_URL: http://scanwebgis-docker.test:63305/geoserver/
    GEOSERVER_PUBLIC_LOCATION: http://scanwebgis-docker.test:63305/geoserver/
    GEOSERVER_LOCATION: http://geoserver:8080/geoserver/
    STATIC_ROOT: /home/web/static
    MEDIA_ROOT: /home/web/media
    GEOIP_PATH: /home/web/media/geoip.db
    ALLOWED_HOSTS: ['scanwebgis-docker.test']
    ADMIN_EMAILS: dimas@kartoza.com
    GEOSERVER_ADMIN_PASSWORD: admingeoserver

geoserver:
  environment:
    GEOSERVER_ADMIN_PASSWORD: admingeoserver
    SITEURL: http://scanwebgis-docker.test:63306/

interpreters:
  inasafe_django:
    name: 'scanwebgis-docker Container'
    domain_alias: 'scanwebgis-docker.test'
    ssh_port: 63303
    pycharm_helpers: /home/web/django_project/.pycharm_helpers
    ipaddress: scanwebgis-docker.test

docker_port_forward:
  django:
    db: 6543
    elastic_search: 9200
    http: 63302
    ssh: 63403
    geoserver: 63305
    karma_tests: 63304
  scanwebgis:
    ssh: 63404
    http: 63306
