# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-31 18:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='output_err',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 18, 38, 38, 168352, tzinfo=utc)),
        ),
    ]
