# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-07 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_auto_20190331_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
