# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-14 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'kobo', '0001_initial'), (b'kobo', '0002_auto_20190214_0519'), (b'kobo', '0003_remove_koboform_client')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KoboForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=200)),
            ],
        ),
    ]
