# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0001_initial_squashed_0003_remove_koboform_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='koboform',
            name='form_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
