# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-05 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0002_koboform_form_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='koboform',
            name='style_attributes',
            field=models.TextField(null=True),
        ),
    ]
