# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-05 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0003_koboform_style_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koboform',
            name='style_attributes',
            field=models.TextField(help_text=b'Separate style attribute with a comma (e.g: tipo_maquina,serie_maquina)', null=True),
        ),
    ]
